reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create]
  resources :subs do
    resources :posts
  end
  resources :posts, only: [:new, :create, :destroy]
end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  belongs_to :user,
    foreign_key: :author,
    class_name: :User

  belongs_to :sub,
    foreign_key: :sub_id,
    class_name: :Sub

end

reddit_clone/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :user,
    foreign_key: :moderator,
    class_name: :User

  has_many :posts,
    foreign_key: :sub_id,
    class_name: :Post

end

reddit_clone/app/models/user.rb
class User < ApplicationRecord
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, :password_digest, :session_token, presence: true
  before_validation :ensure_token

  has_many :subs,
    foreign_key: :moderator,
    class_name: :Sub

  has_many :posts,
    foreign_key: :author,
    class_name: :Post

  attr_reader :password

  def ensure_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    if user && user.is_password?(password)
      user
    else
      nil
    end
  end
end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  def logged_in?
    !!current_user
  end

  def current_user
      @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_token
  end

  def logout
    current_user.reset_token
    session[:token] = nil
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    post = Post.new(post_params)
    post.author = current_user.id
    if post.save
      redirect_to sub_post_url(post)
    else
      flash[:errors] = post.errors.full_messages
      redirect_to new_sub_post_url(post)
    end
  end

  def show
    post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :sub_id)
  end
end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user
      login(user)
      redirect_to subs_url
    else
      flash[:errors] = ["Invalid creds"]
      render :new
    end
  end
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  # before_action :require_login

  def new
  end

  def create
    cat = Sub.new(sub_params)
    cat.moderator = current_user.id

    if cat.save
      redirect_to sub_url(cat)
    else
      flash[:errors] = cat.errors.full_messages
      render :new
    end
  end

  def index
    @cats = Sub.all
  end

  def update
  end

  def edit
  end

  def show
    @cat = Sub.find(params[:id])
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    user = User.new(user_params)

    if user.save
      login(user)
      redirect to subs_url
    else
      flash[:errors] = user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/helpers/user_helper.rb
module UserHelper
end

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= current_user.username %>
      <%= button_to "Sign Out", session_url, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_session_url %>
      <%= link_to "Sign Up", new_user_url %>
    <% end %>

    <% flash[:errors].try(:each) do |err| %>
      <%= err %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

reddit_clone/app/views/posts/show.html.erb
<%= post.title %>

reddit_clone/app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

reddit_clone/app/views/subs/index.html.erb
<h2>All Subs</h2>

<%= link_to "Create a Sub", new_sub_url %>

<% @cats.each do |cat| %>
  <h3><%= link_to cat.title, sub_url(cat) %></h3>
  <h4><%= cat.description %></h4>
<% end %>

reddit_clone/app/views/subs/new.html.erb
<h2>Create a Sub</h2>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<% form_authenticity_token %>">

  <label>Title
    <input type="text" name="sub[title]" value="">
  </label>
  <label>Description
    <input type="text" name="sub[description]" value="">
  </label>

  <input type="submit" name="" value="SUBMIT">
</form>

reddit_clone/app/views/subs/show.html.erb
<%= @cat.title %>
<%= @cat.description %>
<%= @cat.user.username %>

<form action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<% form_authenticity_token %>">
  <label>Title
    <input type="text" name="post[title]" value="">
  </label>
  <input type="hidden" name="post[sub_id]" value="<%= @cat.id %>">

  <input type="submit" name="" value="POST">
</form>

<% @cat.posts.each do |post| %>
  post.title
<% end %>

reddit_clone/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

reddit_clone/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<% form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>
  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Sign Up">
</form>